# 1. Listen only on your wireless interface
interface=wlxe84e06aed7c3
#bind-interfaces
# 2. Define the IP address range to give to connecting users
# This will hand out IPs from .50 to .150, valid for 12 hours
dhcp-range=192.168.1.50,192.168.1.150,255.255.255.0,12h

# 3. Set the Gateway (Router IP) 
# Tells the user's device that your DragonOS machine (192.168.10.1) is the router
dhcp-option=3,192.168.1.1

# 4. Set the DNS Server
# Tells devices to use your DragonOS machine to resolve website names
dhcp-option=6,192.168.1.1

# 5. Captive Portal Spoofing (Crucial for iOS/Android detection)
# This forces specific captive portal detection domains to point directly to your login page
address=/captive.apple.com/192.168.1.1
address=/connectivitycheck.gstatic.com/192.168.1.1
address=/msftconnecttest.com/192.168.1.1
address=/#/192.168.1.1

#address=/conectivitycheck.android.com/192.168.1.1
#no-resolv
#server=8.8.8.8